# Generated by Django 3.1.4 on 2020-12-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monstercatalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
