# Generated by Django 3.1.4 on 2020-12-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monstercatalog', '0002_auto_20201210_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monsterthesisscore',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_score', to='monstercatalog.monster'),
        ),
        migrations.AlterField(
            model_name='monsterthesisscore',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_score', to='monstercatalog.monsterthesis'),
        ),
    ]
